### ISSUE TITLE
Merging modders

### ISSUE THREAD

**Issue by verdverm** [hofstadter-io/mvs#18]
Can we merge modders, so that if I want to only override a portion of a default modder, I don't need to specify the entire config.

while still in yaml format
- try to unmarshal yaml into an already existing modder, add omitempty to the struct's field tags
- if that doesn't work, do by hand, but we should still add the omitempty tags
but then again, will the omitempty result in an empty slice? how do / don't replace a default slice with values, with an empty slice, or not replace it and take the defaults

Once we migrate the .mvsconfig to cue, this probably all gets done there, maybe we do that sooner rather than later

**Comment by verdverm** [comment]
related to #10

**Comment by philipdexter** [comment]
Should be possible now with cue. Basically make a spec with defaults.

**Comment by verdverm** [comment]
This spec w/ defaults would work from a single file, the question is, how do we merge a file with the defaults that are compiled into the binary? I think if we keep the builtin defaults as strings, and then prefix things we read later with the defaults, we might be ok. But not if they start importing things, like imaging having company defaults and just importing the config instead of copying it. There ought to be a method for merging with the CUE api.

**Comment by verdverm** [comment]
btw, I think it makes sense to not have a global configuration and just local + builtin defaults

**Comment by verdverm** [comment]
implemented in #23
