### ISSUE TITLE
v0.0.0 not working

### ISSUE THREAD

**Issue by tombrk** [hofstadter-io/mvs#30]
`README.md` states:

> ```
> github.com/hof-lang/cuemod--cli-golang v0.0.0      # This is latest on HEAD
> ```

This does not seem to be the case:

1. Init CUE module:
```
$ mvs init cue example.com/test
```

2. Modify `cue.mods`
As there is no `mvs get` command, I assume I need to edit `cue.mods` by hand.

```diff
module example.com/test

+ require (
+   github.com/hof-lang/cuemod--cli-golang v0.0.0
+ )

cue 0.1.1
```

3. Run `mvs vendor`
```
$ mvs vendor
Merge   github.com/hof-lang/cuemod--cli-golang@v0.0.0    => github.com/hof-lang/cuemod--cli-golang@v0.0.0
open /home/tbraack/.mvs/mod/cue/github.com/hof-lang/cuemod--cli-golang@v0.0.0: no such file or directory
While calculating billy dir hash for "cue.mod/pkg"
open /home/tbraack/.mvs/mod/cue/github.com/hof-lang/cuemod--cli-golang@v0.0.0: no such file or directory

```

Which repository is taken does not matter, can also reproduce with others. Using a proper tagged version works fine

**Comment by verdverm** [comment]
Give `hof mod vendor` (same args) a try. This tool has been merged into the hof project. I'll update the description to note that.

**Comment by verdverm** [comment]
@sh0rez how did the `hof mod vendor` work for you?

If you are using this for Cue, you'll want to do something like:

```
hof mod init cue github.com/my-handle/cuel-new-project

# (edit cue.mods file)

hof mod vendor cue

# or just "hof mod vendor" works too, discovers and runs all mod systems it finds
```

**Comment by tombrk** [comment]
Hi, unfortunately not, I got exactly the same error message as with mvs

**Comment by verdverm** [comment]
are you using that library? I don't believe it exists anymore, or more likely it is so far out of date, recent versions of mvs/hof don't know how to handle it.

there is a https://github.com/hofstadter-io/hofmod-cli that is the much more advanced and developed version of a CLI generator

**Comment by verdverm** [comment]
```
require (
  github.com/hofstadter-io/hofmod-cli v0.5.8
)
```

**Comment by tombrk** [comment]
Used this only because of the notice in the readme. But I can reproduce the issue with any other library, where v0.0.0 does not work, while real tagged ones do

**Comment by verdverm** [comment]
Ah, I do think I have noticed that, filling a bug over on hof, thanks for reporting!
