### ISSUE TITLE
Support '@' in the org name for requires/replaces

### ISSUE THREAD

**Issue by verdverm** [hofstadter-io/mvs#8]
we can still prefix with a domain name, I think that's part of the syntax

This is mainly for javascript

---
Separate, but came to mind, ...

for both JS and Python, or any other language, where you can import w/o the domain, we should prefix with the package manager domain that would normally be used, during the convert process.

after extracting "import" statements during introspection, we will need to walk back any possible subdirectory packages to find the root of the module and do dependency stuff from there.

**Comment by philipdexter** [comment]
`@` has worked fine with the examples that I've tried. Do you have an example that fails?
